name: Print Text Example

on:
  push:
    branches:
      - main

jobs:
  print-text:
    # runs-on: ubuntu-latest
    uses: actions/checkout@v2

    steps:
    - name: Print Text
      run: |
        echo "Your Text Here"
