name: Print Text Example

on:
  push:
    branches:
      - main

jobs:
  print-text:
    runs-on: ubuntu-latest
    steps:
    - name: Print Text
      run: |
        echo "Your Text Here"
    - uses: neonidian/teams-notify-build-status@v3
      with:
        webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}   # Secret name is "TEAMS_INCOMING_WEBHOOK_URL"
        message: Workflow run passed !!
