name: Print Text Example

on:
  push:
    branches:
      - main

jobs:
  print-text:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print Text
      run: |
        echo "Your Text Here"
    - uses: actions/checkout@v2
    - name: Print text 2
      run: |
        echo "text 2"
